/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedMeConfirmEmailRouteImport } from './routes/_authenticated/me/confirm-email'
import { Route as AuthenticatedMeDependentsRouteImport } from './routes/_authenticated/me/dependents'
import { Route as AuthenticatedMeNotificationsRouteImport } from './routes/_authenticated/me/notifications'
import { Route as AuthenticatedMeProfileRouteImport } from './routes/_authenticated/me/profile'
import { Route as AuthenticatedMeSessionsRouteImport } from './routes/_authenticated/me/sessions'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeConfirmEmailRoute =
  AuthenticatedMeConfirmEmailRouteImport.update({
    id: '/me/confirm-email',
    path: '/me/confirm-email',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeDependentsRoute =
  AuthenticatedMeDependentsRouteImport.update({
    id: '/me/dependents',
    path: '/me/dependents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeNotificationsRoute =
  AuthenticatedMeNotificationsRouteImport.update({
    id: '/me/notifications',
    path: '/me/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeProfileRoute = AuthenticatedMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeSessionsRoute = AuthenticatedMeSessionsRouteImport.update({
  id: '/me/sessions',
  path: '/me/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/me/confirm-email': typeof AuthenticatedMeConfirmEmailRoute
  '/me/dependents': typeof AuthenticatedMeDependentsRoute
  '/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/me/profile': typeof AuthenticatedMeProfileRoute
  '/me/sessions': typeof AuthenticatedMeSessionsRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/me/confirm-email': typeof AuthenticatedMeConfirmEmailRoute
  '/me/dependents': typeof AuthenticatedMeDependentsRoute
  '/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/me/profile': typeof AuthenticatedMeProfileRoute
  '/me/sessions': typeof AuthenticatedMeSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/me/confirm-email': typeof AuthenticatedMeConfirmEmailRoute
  '/_authenticated/me/dependents': typeof AuthenticatedMeDependentsRoute
  '/_authenticated/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/_authenticated/me/profile': typeof AuthenticatedMeProfileRoute
  '/_authenticated/me/sessions': typeof AuthenticatedMeSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/me/confirm-email'
    | '/me/dependents'
    | '/me/notifications'
    | '/me/profile'
    | '/me/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/'
    | '/me/confirm-email'
    | '/me/dependents'
    | '/me/notifications'
    | '/me/profile'
    | '/me/sessions'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/'
    | '/_authenticated/me/confirm-email'
    | '/_authenticated/me/dependents'
    | '/_authenticated/me/notifications'
    | '/_authenticated/me/profile'
    | '/_authenticated/me/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/confirm-email': {
      id: '/_authenticated/me/confirm-email'
      path: '/me/confirm-email'
      fullPath: '/me/confirm-email'
      preLoaderRoute: typeof AuthenticatedMeConfirmEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/dependents': {
      id: '/_authenticated/me/dependents'
      path: '/me/dependents'
      fullPath: '/me/dependents'
      preLoaderRoute: typeof AuthenticatedMeDependentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/notifications': {
      id: '/_authenticated/me/notifications'
      path: '/me/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof AuthenticatedMeNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/profile': {
      id: '/_authenticated/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof AuthenticatedMeProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/sessions': {
      id: '/_authenticated/me/sessions'
      path: '/me/sessions'
      fullPath: '/me/sessions'
      preLoaderRoute: typeof AuthenticatedMeSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMeConfirmEmailRoute: typeof AuthenticatedMeConfirmEmailRoute
  AuthenticatedMeDependentsRoute: typeof AuthenticatedMeDependentsRoute
  AuthenticatedMeNotificationsRoute: typeof AuthenticatedMeNotificationsRoute
  AuthenticatedMeProfileRoute: typeof AuthenticatedMeProfileRoute
  AuthenticatedMeSessionsRoute: typeof AuthenticatedMeSessionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMeConfirmEmailRoute: AuthenticatedMeConfirmEmailRoute,
  AuthenticatedMeDependentsRoute: AuthenticatedMeDependentsRoute,
  AuthenticatedMeNotificationsRoute: AuthenticatedMeNotificationsRoute,
  AuthenticatedMeProfileRoute: AuthenticatedMeProfileRoute,
  AuthenticatedMeSessionsRoute: AuthenticatedMeSessionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
