/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedFieldsRouteImport } from './routes/_authenticated/fields'
import { Route as AuthenticatedHandicapsRouteImport } from './routes/_authenticated/handicaps'
import { Route as AuthenticatedMeConfirmEmailRouteImport } from './routes/_authenticated/me/confirm-email'
import { Route as AuthenticatedMeDependentsRouteImport } from './routes/_authenticated/me/dependents'
import { Route as AuthenticatedMeNotificationsRouteImport } from './routes/_authenticated/me/notifications'
import { Route as AuthenticatedMeProfileRouteImport } from './routes/_authenticated/me/profile'
import { Route as AuthenticatedMeSessionsRouteImport } from './routes/_authenticated/me/sessions'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedUsersUserIdRouteImport } from './routes/_authenticated/users/$userId'
import { Route as AuthenticatedUsersNewRouteImport } from './routes/_authenticated/users/new'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFieldsRoute = AuthenticatedFieldsRouteImport.update({
  id: '/fields',
  path: '/fields',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHandicapsRoute = AuthenticatedHandicapsRouteImport.update({
  id: '/handicaps',
  path: '/handicaps',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeConfirmEmailRoute =
  AuthenticatedMeConfirmEmailRouteImport.update({
    id: '/me/confirm-email',
    path: '/me/confirm-email',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeDependentsRoute =
  AuthenticatedMeDependentsRouteImport.update({
    id: '/me/dependents',
    path: '/me/dependents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeNotificationsRoute =
  AuthenticatedMeNotificationsRouteImport.update({
    id: '/me/notifications',
    path: '/me/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeProfileRoute = AuthenticatedMeProfileRouteImport.update({
  id: '/me/profile',
  path: '/me/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeSessionsRoute = AuthenticatedMeSessionsRouteImport.update({
  id: '/me/sessions',
  path: '/me/sessions',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersUserIdRoute =
  AuthenticatedUsersUserIdRouteImport.update({
    id: '/users/$userId',
    path: '/users/$userId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersNewRoute = AuthenticatedUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/fields': typeof AuthenticatedFieldsRoute
  '/handicaps': typeof AuthenticatedHandicapsRoute
  '/me/confirm-email': typeof AuthenticatedMeConfirmEmailRoute
  '/me/dependents': typeof AuthenticatedMeDependentsRoute
  '/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/me/profile': typeof AuthenticatedMeProfileRoute
  '/me/sessions': typeof AuthenticatedMeSessionsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/fields': typeof AuthenticatedFieldsRoute
  '/handicaps': typeof AuthenticatedHandicapsRoute
  '/': typeof AuthenticatedIndexRoute
  '/me/confirm-email': typeof AuthenticatedMeConfirmEmailRoute
  '/me/dependents': typeof AuthenticatedMeDependentsRoute
  '/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/me/profile': typeof AuthenticatedMeProfileRoute
  '/me/sessions': typeof AuthenticatedMeSessionsRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/users/new': typeof AuthenticatedUsersNewRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/fields': typeof AuthenticatedFieldsRoute
  '/_authenticated/handicaps': typeof AuthenticatedHandicapsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/me/confirm-email': typeof AuthenticatedMeConfirmEmailRoute
  '/_authenticated/me/dependents': typeof AuthenticatedMeDependentsRoute
  '/_authenticated/me/notifications': typeof AuthenticatedMeNotificationsRoute
  '/_authenticated/me/profile': typeof AuthenticatedMeProfileRoute
  '/_authenticated/me/sessions': typeof AuthenticatedMeSessionsRoute
  '/_authenticated/users/$userId': typeof AuthenticatedUsersUserIdRoute
  '/_authenticated/users/new': typeof AuthenticatedUsersNewRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/calendar'
    | '/fields'
    | '/handicaps'
    | '/me/confirm-email'
    | '/me/dependents'
    | '/me/notifications'
    | '/me/profile'
    | '/me/sessions'
    | '/users/$userId'
    | '/users/new'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/calendar'
    | '/fields'
    | '/handicaps'
    | '/'
    | '/me/confirm-email'
    | '/me/dependents'
    | '/me/notifications'
    | '/me/profile'
    | '/me/sessions'
    | '/users/$userId'
    | '/users/new'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invitation'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/_authenticated/calendar'
    | '/_authenticated/fields'
    | '/_authenticated/handicaps'
    | '/_authenticated/'
    | '/_authenticated/me/confirm-email'
    | '/_authenticated/me/dependents'
    | '/_authenticated/me/notifications'
    | '/_authenticated/me/profile'
    | '/_authenticated/me/sessions'
    | '/_authenticated/users/$userId'
    | '/_authenticated/users/new'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fields': {
      id: '/_authenticated/fields'
      path: '/fields'
      fullPath: '/fields'
      preLoaderRoute: typeof AuthenticatedFieldsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/handicaps': {
      id: '/_authenticated/handicaps'
      path: '/handicaps'
      fullPath: '/handicaps'
      preLoaderRoute: typeof AuthenticatedHandicapsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/confirm-email': {
      id: '/_authenticated/me/confirm-email'
      path: '/me/confirm-email'
      fullPath: '/me/confirm-email'
      preLoaderRoute: typeof AuthenticatedMeConfirmEmailRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/dependents': {
      id: '/_authenticated/me/dependents'
      path: '/me/dependents'
      fullPath: '/me/dependents'
      preLoaderRoute: typeof AuthenticatedMeDependentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/notifications': {
      id: '/_authenticated/me/notifications'
      path: '/me/notifications'
      fullPath: '/me/notifications'
      preLoaderRoute: typeof AuthenticatedMeNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/profile': {
      id: '/_authenticated/me/profile'
      path: '/me/profile'
      fullPath: '/me/profile'
      preLoaderRoute: typeof AuthenticatedMeProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/me/sessions': {
      id: '/_authenticated/me/sessions'
      path: '/me/sessions'
      fullPath: '/me/sessions'
      preLoaderRoute: typeof AuthenticatedMeSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/$userId': {
      id: '/_authenticated/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/new': {
      id: '/_authenticated/users/new'
      path: '/users/new'
      fullPath: '/users/new'
      preLoaderRoute: typeof AuthenticatedUsersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedFieldsRoute: typeof AuthenticatedFieldsRoute
  AuthenticatedHandicapsRoute: typeof AuthenticatedHandicapsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMeConfirmEmailRoute: typeof AuthenticatedMeConfirmEmailRoute
  AuthenticatedMeDependentsRoute: typeof AuthenticatedMeDependentsRoute
  AuthenticatedMeNotificationsRoute: typeof AuthenticatedMeNotificationsRoute
  AuthenticatedMeProfileRoute: typeof AuthenticatedMeProfileRoute
  AuthenticatedMeSessionsRoute: typeof AuthenticatedMeSessionsRoute
  AuthenticatedUsersUserIdRoute: typeof AuthenticatedUsersUserIdRoute
  AuthenticatedUsersNewRoute: typeof AuthenticatedUsersNewRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedFieldsRoute: AuthenticatedFieldsRoute,
  AuthenticatedHandicapsRoute: AuthenticatedHandicapsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMeConfirmEmailRoute: AuthenticatedMeConfirmEmailRoute,
  AuthenticatedMeDependentsRoute: AuthenticatedMeDependentsRoute,
  AuthenticatedMeNotificationsRoute: AuthenticatedMeNotificationsRoute,
  AuthenticatedMeProfileRoute: AuthenticatedMeProfileRoute,
  AuthenticatedMeSessionsRoute: AuthenticatedMeSessionsRoute,
  AuthenticatedUsersUserIdRoute: AuthenticatedUsersUserIdRoute,
  AuthenticatedUsersNewRoute: AuthenticatedUsersNewRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
